### ISSUE TITLE
上游仓库更新

### ISSUE THREAD

**Issue by Moenupa** [KuroseReza/AutoMihoyoBBS_with_Actions#7]
就在今天 github 上游仓库寄了（悲）。
我看 gitee 上好像有 mirror，要不考虑换下链接？（维护情况我就不太了解）
我手上也有 private 的 mirror（昨天整的，巧了不是），需要的话我可以帮忙。

还有提个小建议
`add_cookie`需要repo的`write`权限，可以在readme加一个提醒把repo里`Settings`-`Actions`-`General`-`Workflow permissions`的权限改一下（默认好像是第二个只有read）

<img width="768" alt="image" src="https://user-images.githubusercontent.com/49304833/216625560-11c32f3f-70f1-4e1b-82e2-5d2b0c28e449.png">

**Comment by Moenupa** [comment]
新 repo 位置：https://github.com/Womsxd/MihoyoBBSTools

`git clone` 代码替换：

```yml
- name: Clone source
      uses: actions/checkout@v3
      with:
        repository: Womsxd/MihoyoBBSTools
        path: mihoyo
```
